### ISSUE TITLE
Support http proxy

### ISSUE THREAD

**Issue by djannot** [Aloisius/hadoop-s3a#11]
Hi,

Could you please add an option to specify a proxy ?

You should add something like that in S3AFileSystem.java:
awsConf..setProxyHost("192.168.2.12");
awsConf.clientCfg.setProxyPort(80);

Thanks

**Comment by thodemoor** [comment]
This codebase has been incorporated into Apache Hadoop (also under the name
s3a). The proxy server support you are asking for is being added in 2.7,
which will be released this month.

Thomas Demoor

**Comment by djannot** [comment]
Thanks !
