### ISSUE TITLE
Is s3a support AWS SSE-KMS encryption while uploading data from hdfs to s3?

### ISSUE THREAD

**Issue by error804** [Aloisius/hadoop-s3a#13]
Hi,

We are trying to upload data to s3 destination with file that need to be encrypted with SSE-KMS keys. Does the s3a file system implementaion support this?

We were able to copy SSE-KMS encypted files from the s3 bucket to AWS EMR cluster's HDFS using command:-

<code>
hadoop fs -cp s3a://bucketName/data/  hdfs://testip/user/hdfs/
</code>

But we were unable to copy files from EMR cluster's HDFS to s3 bucket with AWS SSE-KMS encryption. Does it also support multipart-file upload?

Hope to hear from you soon,
error804.

**Comment by error804** [comment]
Thanks,

Finally we were able to copy data from s3 to hdfs and hdfs to s3 with SSE-KMS encryption.

Regards,
error804.

**Comment by fedecz** [comment]
hey @error804 , may I ask you how were you able to copy data to/from S3a/hdfs using SSE-KMS ? Thanks

Fede

**Comment by error804** [comment]
Modified some of the github code to add encryption

On Wednesday, May 18, 2016, Federico Czerwinski <notifications@github.com>
wrote:

> hey @error804 <https://github.com/error804> , may I ask you how were you
> able to copy data to/from S3a/hdfs using SSE-KMS ? Thanks
>
> Fede
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Aloisius/hadoop-s3a/issues/13#issuecomment-219923549>
>


-- 
@error804
